const allBlogs = [
    {
        category:'1',
        logtime:'2022-11-12',
        src:'/assets/images/Blogs/b1.webp',
        heading:'7 Latest Innovations in Robotics',
        description:'An automated device created by Universal Robots known as UR3 can build its own replacement parts on the fly. The cute and nimble robot can handle a variety of tasks, such as gluing, painting, soldering, and grasping...',
    },
    {
        category:'1',
        logtime:'2022-11-10',
        src:'/assets/images/Blogs/b2.webp',
        heading:'How to design app in 6 easy steps',
        description:'Designing an app is always challenging, as it requires a complete understanding of what you can bring to the table. With all...',
    },
    {
        category:'2',
        logtime:'2022-10-31',
        src:'/assets/images/Blogs/b3.webp',
        heading:'Leonid Meteor Shower 2022',
        description:"Leonid Meteor Shower 2022: Here's How To Watch The Night Sky Light Up This Month, There are other 4 prospect buyers including *drum rolls* Amazon boss Jeff Bezos! Quires a complete understanding of what you can bring to the table. With all...",
    },
    {
        category:'1',
        logtime:'2022-10-20',
        src:'/assets/images/Blogs/b4.webp',
        heading:'Machines are learning humans are forgetting',
        description:"Assuming that the Right to Be Forgotten is a valuable right that should be protected, and given that this article proves the impracticability of applying the Right to Be Forgotten in machine learning environments...",
    },
    {
        category:'2',
        logtime:'2022-10-10',
        src:'/assets/images/Blogs/b5.webp',
        heading:'UX is not UI',
        description:"While UX targets optimizing a product or a service to make it easy, effective and pleasant for someone to use, UI focuses on the visual components, sensations and interactivity...",
    },
    {
        category:'1',
        logtime:'2022-11-12',
        src:'/assets/images/Blogs/b2.webp',
        heading:'7 Latest Innovations in Robotics',
        description:'An automated device created by Universal Robots known as UR3 can build its own replacement parts on the fly. The cute and nimble robot can handle a variety of tasks, such as gluing, painting, soldering, and grasping...',
    },
    {
        category:'2',
        logtime:'2022-11-10',
        src:'/assets/images/Blogs/b3.webp',
        heading:'How to design app in 6 easy steps',
        description:'Designing an app is always challenging, as it requires a complete understanding of what you can bring to the table. With all...',
    },
    {
        category:'1',
        logtime:'2022-10-31',
        src:'/assets/images/Blogs/b3.webp',
        heading:'Leonid Meteor Shower 2022',
        description:"Leonid Meteor Shower 2022: Here's How To Watch The Night Sky Light Up This Month, There are other 4 prospect buyers including *drum rolls* Amazon boss Jeff Bezos! Quires a complete understanding of what you can bring to the table. With all...",
    },
    {
        category:'1',
        logtime:'2022-10-20',
        src:'/assets/images/Blogs/b4.webp',
        heading:'Machines are learning humans are forgetting',
        description:"Assuming that the Right to Be Forgotten is a valuable right that should be protected, and given that this article proves the impracticability of applying the Right to Be Forgotten in machine learning environments...",
    },
    {
        category:'2',
        logtime:'2022-10-10',
        src:'/assets/images/Blogs/b5.webp',
        heading:'UX is not UI',
        description:"While UX targets optimizing a product or a service to make it easy, effective and pleasant for someone to use, UI focuses on the visual components, sensations and interactivity...",
    },
    {
        category:'2',
        logtime:'2022-11-12',
        src:'/assets/images/Blogs/b5.webp',
        heading:'7 Latest Innovations in Robotics',
        description:'An automated device created by Universal Robots known as UR3 can build its own replacement parts on the fly. The cute and nimble robot can handle a variety of tasks, such as gluing, painting, soldering, and grasping...',
    },
    {
        category:'2',
        logtime:'2022-11-10',
        src:'/assets/images/Blogs/b2.webp',
        heading:'How to design app in 6 easy steps',
        description:'Designing an app is always challenging, as it requires a complete understanding of what you can bring to the table. With all...',
    },
    {
        category:'2',
        logtime:'2022-10-31',
        src:'/assets/images/Blogs/b3.webp',
        heading:'Leonid Meteor Shower 2022',
        description:"Leonid Meteor Shower 2022: Here's How To Watch The Night Sky Light Up This Month, There are other 4 prospect buyers including *drum rolls* Amazon boss Jeff Bezos! Quires a complete understanding of what you can bring to the table. With all...",
    },
    {
        category:'1',
        logtime:'2022-10-20',
        src:'/assets/images/Blogs/b4.webp',
        heading:'Machines are learning humans are forgetting',
        description:"Assuming that the Right to Be Forgotten is a valuable right that should be protected, and given that this article proves the impracticability of applying the Right to Be Forgotten in machine learning environments...",
    },
    {
        category:'1',
        logtime:'2022-10-10',
        src:'/assets/images/Blogs/b5.webp',
        heading:'UX is not UI',
        description:"While UX targets optimizing a product or a service to make it easy, effective and pleasant for someone to use, UI focuses on the visual components, sensations and interactivity...",
    },
    {
        category:'1',
        logtime:'2022-11-12',
        src:'/assets/images/Blogs/b4.webp',
        heading:'7 Latest Innovations in Robotics',
        description:'An automated device created by Universal Robots known as UR3 can build its own replacement parts on the fly. The cute and nimble robot can handle a variety of tasks, such as gluing, painting, soldering, and grasping...',
    },
    {
        category:'1',
        logtime:'2022-11-10',
        src:'/assets/images/Blogs/b2.webp',
        heading:'How to design app in 6 easy steps',
        description:'Designing an app is always challenging, as it requires a complete understanding of what you can bring to the table. With all...',
    },
    {
        category:'2',
        logtime:'2022-10-31',
        src:'/assets/images/Blogs/b3.webp',
        heading:'Leonid Meteor Shower 2022',
        description:"Leonid Meteor Shower 2022: Here's How To Watch The Night Sky Light Up This Month, There are other 4 prospect buyers including *drum rolls* Amazon boss Jeff Bezos! Quires a complete understanding of what you can bring to the table. With all...",
    },
    {
        category:'2',
        logtime:'2022-10-20',
        src:'/assets/images/Blogs/b4.webp',
        heading:'Machines are learning humans are forgetting',
        description:"Assuming that the Right to Be Forgotten is a valuable right that should be protected, and given that this article proves the impracticability of applying the Right to Be Forgotten in machine learning environments...",
    },
    {
        category:'2',
        logtime:'2022-10-10',
        src:'/assets/images/Blogs/b5.webp',
        heading:'UX is not UI',
        description:"While UX targets optimizing a product or a service to make it easy, effective and pleasant for someone to use, UI focuses on the visual components, sensations and interactivity...",
    }
]
export default function getBlogsData(){
    return allBlogs
}